# Generated by Django 3.0.8 on 2020-07-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото софта')),
                ('title', models.CharField(max_length=20, verbose_name='Название софта')),
                ('published', models.DateField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Софт',
                'verbose_name_plural': 'Софты',
                'ordering': ['-published'],
            },
        ),
    ]
