# Generated by Django 3.0.8 on 2020-07-06 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Фото категории'),
            preserve_default=False,
        ),
    ]
