# Generated by Django 3.0.8 on 2020-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200706_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(upload_to='', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='soft',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Фото софта'),
        ),
    ]
