# Generated by Django 3.0.8 on 2020-07-06 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200706_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, verbose_name='Субкатегория'),
            preserve_default=False,
        ),
    ]
