# Generated by Django 3.0.8 on 2020-07-06 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200706_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'ПодКатегория', 'verbose_name_plural': 'ПодКатегории'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category', verbose_name='Категория'),
        ),
    ]
