# Generated by Django 3.0.8 on 2020-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200725_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soft',
            old_name='soft_file',
            new_name='file',
        ),
    ]
