# Generated by Django 3.0.8 on 2020-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200725_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название софта'),
        ),
    ]
