# Generated by Django 3.0.8 on 2020-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200727_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название софта'),
        ),
    ]
