# Generated by Django 3.0.9 on 2020-08-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200727_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft',
            name='downloads',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скачивания'),
        ),
    ]
