# Generated by Django 3.0.9 on 2020-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_soft_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft',
            name='downloads',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скачивания'),
        ),
    ]
