# Generated by Django 3.0.9 on 2020-08-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200811_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
